#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt update
sudo apt install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

sudo sed -i "$ a\listen 28056-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 28056-web-02 3.238.248.146:80 check\n\tserver 28056-web-01 3.238.204.225:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
